baseUrl: https://emc2hf.github.io
languageCode: en-us
theme: PaperMod
copyright: '<a href="https://x.com/emc2hf">@emc2hf</a>'
pagerSize: 10
permalinks:
  posts: /blog/:year/:month/:day/:title/
googleAnalytics: UA-44457032-2

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  env: production
  author: Pol Sarís
  keywords: [blog,hack,ctf,emc2hf,pentester,red team,attack,writeup]
  contentTypeName: posts
  defaultTheme: auto
  showMenuItems: 3 
  showReadingTime: true
  ShowShareButtons: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

  homeInfoParams:
    Title: "Welcome to my Blog!"
    Content: >
      Welcome to my Cybersecurity blog!  

      Here you'll find all of my security research and CTF writeups in detail. You can also read my posts on my [Medium](https://medium.com/@emc2hf) space!
      

      For more about me, check out the [about me](about/) section!

  socialIcons:
    - name: twitter
      url: "https://x.com/emc2hf"
    - name: github
      url: "https://github.com/emc2hf-org"
    - name: medium
      url: "https://medium.com/@emc2hf"
    - name: rss
      url: "index.xml"

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  tableOfContents:
    endLevel: 4
    startLevel: 1

languages:
  en:
    title: |
      emc2hf Blog
    subtitle: CTF Writeups and Security Research Blog
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    lastModDisplay: 2006-01-02
    
    params:
      logo:
        logoText: |
          emc2hf Blog
        logoHomeLink: /
    
    menu:
      main:
      - name: Archive
        url: archives
      - identifier: search
        name: Search
        url: search/
      - identifier: categories
        name: Categories
        url: /categories
      - identifier: writeups
        name: CTF Writeups
        url: /categories/writeup
      - identifier: research
        name: Security Research
        url: /categories/research  

minify:
  disableXML: true
  minifyOutput: true
