baseUrl: https://leonjza.github.io
languageCode: en-us
theme: hello-friend
copyright: '<a href="https://twitter.com/leonjza">@leonjza</a>'
paginate: 10
permalinks:
  posts: /blog/:year/:month/:day/:title/
googleAnalytics: UA-44457032-2

params:
  contentTypeName: posts
  defaultTheme: dark
  showMenuItems: 3 
  showReadingTime: true
  toc: true

markup:
  tableOfContents:
    endLevel: 4
    startLevel: 1

languages:
  en:
    title: |
      #!/bin/note
    subtitle: a checkbox uncheckers notepad
    keywords: 'blog,hack,ctf,leonjza,pentester,red team,attack'
    menuMore: Show more
    writtenBy: Written by
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    lastModDisplay: 2006-01-02
    
    params:
      logo:
        logoText: |
          #!/bin/note
        logoHomeLink: /
    
    menu:
      main:
      - identifier: posts
        name: Posts
        url: /posts
      - identifier: categories
        name: Categories
        url: /categories

minify:
  minifyOutput: true
